#!/bin/sh
python run_training.py lsst_data DeepCNN informed
python run_training.py lsst_data ShallowGRU informed
python run_training.py lsst_data SmallImageFC informed
python run_training.py lsst_data LoNet informed
python run_training.py lsst_data GloNet informed
python run_training.py lsst_data MuNet informed
python run_training.py lsst_data EvidentialLoNet noninformed
python run_training.py lsst_data EvidentialMuNet noninformed
python run_training.py lsst_data LoNet noninformed
python run_training.py lsst_data GloNet noninformed
python run_training.py lsst_data MuNet noninformed
python run_training.py high_cad_data DeepCNN informed
python run_training.py high_cad_data ShallowGRU informed
python run_training.py high_cad_data SmallImageFC informed
python run_training.py high_cad_data LoNet informed
python run_training.py high_cad_data GloNet informed
python run_training.py high_cad_data MuNet informed
python run_training.py high_cad_data EvidentialLoNet noninformed
python run_training.py high_cad_data EvidentialMuNet noninformed
python run_training.py high_cad_data LoNet noninformed
python run_training.py high_cad_data GloNet noninformed
python run_training.py high_cad_data MuNet noninformed
python run_training.py full_data DeepCNN informed
python run_training.py full_data ShallowGRU informed
python run_training.py full_data SmallImageFC informed
python run_training.py full_data LoNet informed
python run_training.py full_data GloNet informed
python run_training.py full_data MuNet informed
python run_training.py full_data EvidentialLoNet noninformed
python run_training.py full_data EvidentialMuNet noninformed
python run_training.py full_data LoNet noninformed
python run_training.py full_data GloNet noninformed
python run_training.py full_data MuNet noninformed
python run_training.py des_deep_data DeepCNN informed
python run_training.py des_deep_data ShallowGRU informed
python run_training.py des_deep_data SmallImageFC informed
python run_training.py des_deep_data LoNet informed
python run_training.py des_deep_data GloNet informed
python run_training.py des_deep_data MuNet informed
python run_training.py des_deep_data EvidentialLoNet noninformed
python run_training.py des_deep_data EvidentialMuNet noninformed
python run_training.py des_deep_data LoNet noninformed
python run_training.py des_deep_data GloNet noninformed
python run_training.py des_deep_data MuNet noninformed
python run_svm_ensemble.py